services:
  postgres:
    build:
      context: .
      dockerfile: db.Dockerfile
    container_name: healthcare_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Warmia50587
      POSTGRES_DB: healthcare_cost_navigator
      # Performance tuning settings - AGGRESSIVE 32GB WORKSTATION
      POSTGRES_SHARED_BUFFERS: 8GB
      POSTGRES_WORK_MEM: 64MB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 24GB
      POSTGRES_MAX_PARALLEL_WORKERS_PER_GATHER: 4
      POSTGRES_MAINTENANCE_WORK_MEM: 2GB
      POSTGRES_JIT: "on"
      POSTGRES_RANDOM_PAGE_COST: 1.1
      POSTGRES_EFFECTIVE_IO_CONCURRENCY: 300
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./etl/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d healthcare_cost_navigator"]
      interval: 10s
      timeout: 5s
      retries: 5


  api:
    build: .
    container_name: healthcare_api
    env_file:
      - .env           
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:Warmia50587@postgres:5432/healthcare_cost_navigator
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./data:/app/data
      - ./app:/app/app
    restart: unless-stopped

volumes:
  postgres_data:
