version: '3.8'

services:
  postgres:
    image: postgis/postgis:17-3.5
    container_name: healthcare_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Warmia50587
      POSTGRES_DB: healthcare_cost_navigator
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d healthcare_cost_navigator"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: healthcare_api
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:Warmia50587@postgres:5432/healthcare_cost_navigator
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./data:/app/data
    restart: unless-stopped

volumes:
  postgres_data:
